23/09/22 21:22:39 sp_servicios_g 
23/09/22 21:28:59 sp_servicios_g
23/09/22 21:30:07 sp_servicios_g
26/09/22 01:28:23 sp_servicios_b Ha ocurrido un error(42000). 42000 1318 Incorrect number of arguments for PROCEDURE u808450138_checkup.sp_servicios_b; expected 2, got 1
26/09/22 01:28:37 sp_servicios_b Ha ocurrido un error(42000). 42000 1318 Incorrect number of arguments for PROCEDURE u808450138_checkup.sp_servicios_b; expected 2, got 1
26/09/22 01:29:18 sp_servicios_b Ha ocurrido un error(42000). 42000 1318 Incorrect number of arguments for PROCEDURE u808450138_checkup.sp_servicios_b; expected 2, got 1
26/09/22 01:32:02 sp_servicios_b Ha ocurrido un error(42S22). 42S22 1054 Unknown column 'pac.ID_SERVICIO' in 'order clause'
26/09/22 01:46:53 sp_servicios_b Ha ocurrido un error(42000). 42000 1318 Incorrect number of arguments for PROCEDURE u808450138_checkup.sp_servicios_b; expected 2, got 1
26/09/22 15:29:53 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [2002] Se produjo un error durante el intento de conexiï¿½n ya que la parte conectada no respondiï¿½ adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexiï¿½n establecida ya que el host conectado no ha podido responder.

26/09/22 15:30:15 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [2002] Se produjo un error durante el intento de conexiï¿½n ya que la parte conectada no respondiï¿½ adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexiï¿½n establecida ya que el host conectado no ha podido responder.

26/09/22 15:30:29 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [2002] Se produjo un error durante el intento de conexiï¿½n ya que la parte conectada no respondiï¿½ adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexiï¿½n establecida ya que el host conectado no ha podido responder.

26/09/22 15:30:32 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [2002] Se produjo un error durante el intento de conexiï¿½n ya que la parte conectada no respondiï¿½ adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexiï¿½n establecida ya que el host conectado no ha podido responder.

26/09/22 15:32:24 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [2002] Se produjo un error durante el intento de conexiï¿½n ya que la parte conectada no respondiï¿½ adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexiï¿½n establecida ya que el host conectado no ha podido responder.

26/09/22 15:36:07 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [2002] Se produjo un error durante el intento de conexiï¿½n ya que la parte conectada no respondiï¿½ adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexiï¿½n establecida ya que el host conectado no ha podido responder.

26/09/22 15:36:07 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [2002] Se produjo un error durante el intento de conexiï¿½n ya que la parte conectada no respondiï¿½ adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexiï¿½n establecida ya que el host conectado no ha podido responder.
<<<<<<< Updated upstream

26/09/22 17:08:47 sp_servicios_b Ha ocurrido un error(42000). 42000 1318 Incorrect number of arguments for PROCEDURE u808450138_checkup.sp_servicios_b; expected 3, got 2
26/09/22 17:19:03 sp_servicios_b Ha ocurrido un error(42S22). 42S22 1054 Unknown column 'serv.ID_USUARIO' in 'on clause'
26/09/22 17:21:22 sp_servicios_b Ha ocurrido un error(42S22). 42S22 1054 Unknown column 'are.AREA_ID' in 'field list'
26/09/22 17:21:25 sp_servicios_b Ha ocurrido un error(42S22). 42S22 1054 Unknown column 'are.AREA_ID' in 'field list'
26/09/22 17:21:27 sp_servicios_b Ha ocurrido un error(42S22). 42S22 1054 Unknown column 'are.AREA_ID' in 'field list'
26/09/22 17:21:28 sp_servicios_b Ha ocurrido un error(42S22). 42S22 1054 Unknown column 'are.AREA_ID' in 'field list'
=======
>>>>>>> Stashed changes
26/09/22 21:22:37 sp_servicios_b Ha ocurrido un error(42S22). 42S22 1054 Unknown column 'cat.CODGIO' in 'field list'
26/09/22 21:23:55 sp_servicios_b Ha ocurrido un error(42S22). 42S22 1054 Unknown column 'cat.CODGIO' in 'field list'
26/09/22 21:23:58 sp_servicios_b Ha ocurrido un error(42S22). 42S22 1054 Unknown column 'cat.CODGIO' in 'field list'
27/09/22 20:35:14 sp_servicios_g Ha ocurrido un error(23000). 23000 1452 Cannot add or update a child row: a foreign key constraint fails (`u808450138_checkup`.`servicios`, CONSTRAINT `FK_REFERENCE_13` FOREIGN KEY (`PADRE`) REFERENCES `servicios` (`ID_SERVICIO`))
28/09/22 19:16:26 sp_laboratorio_equipos_g Ha ocurrido un error(23000). 23000 1062 Duplicate entry '0' for key 'PRIMARY'
28/09/22 19:16:31 sp_laboratorio_equipos_g Ha ocurrido un error(23000). 23000 1062 Duplicate entry '0' for key 'PRIMARY'
28/09/22 19:48:54 sp_laboratorio_equipos_g Ha ocurrido un error(23000). 23000 1062 Duplicate entry '0' for key 'PRIMARY'
28/09/22 19:49:36 sp_laboratorio_equipos_g Ha ocurrido un error(23000). 23000 1062 Duplicate entry '0' for key 'PRIMARY'
28/09/22 19:54:28 sp_laboratorio_equipos_g Ha ocurrido un error(23000). 23000 1062 Duplicate entry '0' for key 'PRIMARY'
29/09/22 01:25:59 sp_servicios_g Ha ocurrido un error(42000). 42000 1318 Incorrect number of arguments for PROCEDURE u808450138_checkup.sp_servicios_g; expected 20, got 19
29/09/22 01:28:08 sp_laboratorio_equipos_g Ha ocurrido un error(23000). 23000 1062 Duplicate entry '0' for key 'PRIMARY'
30/09/22 16:58:17 sp_laboratorio_equipos_g Ha ocurrido un error(23000). 23000 1062 Duplicate entry '0' for key 'PRIMARY'
30/09/22 17:00:03 sp_laboratorio_equipos_g Ha ocurrido un error(23000). 23000 1062 Duplicate entry '0' for key 'PRIMARY'
30/09/22 17:01:37 sp_laboratorio_equipos_g Ha ocurrido un error(23000). 23000 1062 Duplicate entry '0' for key 'PRIMARY'
30/09/22 17:03:13 sp_laboratorio_equipos_g Ha ocurrido un error(23000). 23000 1062 Duplicate entry '0' for key 'PRIMARY'
30/09/22 17:06:06 sp_laboratorio_equipos_g Ha ocurrido un error(23000). 23000 1062 Duplicate entry '0' for key 'PRIMARY'
30/09/22 17:06:16 sp_laboratorio_equipos_g Ha ocurrido un error(23000). 23000 1062 Duplicate entry '0' for key 'PRIMARY'
30/09/22 17:07:44 sp_laboratorio_equipos_g Ha ocurrido un error(23000). 23000 1062 Duplicate entry '0' for key 'PRIMARY'
30/09/22 17:08:01 sp_laboratorio_equipos_g Ha ocurrido un error(23000). 23000 1062 Duplicate entry '0' for key 'PRIMARY'
30/09/22 17:08:04 sp_laboratorio_equipos_g Ha ocurrido un error(23000). 23000 1062 Duplicate entry '0' for key 'PRIMARY'
30/09/22 17:11:11 sp_laboratorio_equipos_g Ha ocurrido un error(23000). 23000 1062 Duplicate entry '0' for key 'PRIMARY'
01/10/22 15:35:42 sp_servicios_g Ha ocurrido un error(42000). 42000 1318 Incorrect number of arguments for PROCEDURE u808450138_checkup.sp_servicios_g; expected 21, got 19
01/10/22 15:38:19 sp_servicios_g Ha ocurrido un error(42000). 42000 1318 Incorrect number of arguments for PROCEDURE u808450138_checkup.sp_servicios_g; expected 20, got 19
01/10/22 15:41:11 sp_servicios_g Ha ocurrido un error(42S22). 42S22 1054 Unknown column '_abreviatura' in 'where clause'
01/10/22 15:45:33 sp_servicios_g Ha ocurrido un error(42S22). 42S22 1054 Unknown column '_abreviatura' in 'where clause'
01/10/22 15:54:49 sp_pacientes_b Ha ocurrido un error(42000). 42000 1318 Incorrect number of arguments for PROCEDURE u808450138_checkup.sp_pacientes_b; expected 2, got 1
01/10/22 15:55:42 sp_pacientes_b Ha ocurrido un error(42000). 42000 1318 Incorrect number of arguments for PROCEDURE u808450138_checkup.sp_pacientes_b; expected 2, got 1
05/10/22 14:45:11 sp_pacientes_g Ha ocurrido un error(42000). 42000 1318 Incorrect number of arguments for PROCEDURE u808450138_checkup.sp_pacientes_g; expected 24, got 2
05/10/22 14:45:50 sp_pacientes_g Ha ocurrido un error(42000). 42000 1318 Incorrect number of arguments for PROCEDURE u808450138_checkup.sp_pacientes_g; expected 24, got 2
07/10/22 20:53:00 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [2002] Se ha intentado una operación de socket en una red no accesible.

07/10/22 20:54:24 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [2006] MySQL server has gone away
07/10/22 20:54:24 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [2002] Se ha intentado una operación de socket en un host no accesible.

07/10/22 20:54:24 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [2002] Se ha intentado una operación de socket en un host no accesible.

07/10/22 20:54:24 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [2002] Se ha intentado una operación de socket en un host no accesible.

10/10/22 16:13:00 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [2002] Se ha intentado una operación de socket en un host no accesible.

10/10/22 16:13:06 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [2002] Se ha intentado una operación de socket en un host no accesible.

10/10/22 16:13:07 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [2002] Se ha intentado una operación de socket en un host no accesible.

10/10/22 16:13:22 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [2002] Se ha intentado una operación de socket en un host no accesible.

10/10/22 16:13:22 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [2002] Se ha intentado una operación de socket en un host no accesible.

10/10/22 16:13:25 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [2002] Se ha intentado una operación de socket en un host no accesible.

10/10/22 16:13:26 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [2002] Se ha intentado una operación de socket en un host no accesible.

11/10/22 17:41:38 sp_servicios_g Ha ocurrido un error(23000). 23000 1452 Cannot add or update a child row: a foreign key constraint fails (`u808450138_checkup`.`servicios`, CONSTRAINT `FK_REFERENCE_14_1` FOREIGN KEY (`AREA_ID`) REFERENCES `areas` (`ID_AREA`) ON DELETE CASCADE ON UPDATE CASCADE)
11/10/22 17:46:00 sp_servicios_b Ha ocurrido un error(42S22). 42S22 1054 Unknown column 'serv.PADRE' in 'field list'
11/10/22 17:46:03 sp_servicios_b Ha ocurrido un error(42S22). 42S22 1054 Unknown column 'serv.PADRE' in 'field list'
11/10/22 17:46:14 sp_servicios_b Ha ocurrido un error(42S22). 42S22 1054 Unknown column 'serv.PADRE' in 'field list'
11/10/22 17:46:17 sp_servicios_b Ha ocurrido un error(42S22). 42S22 1054 Unknown column 'serv.PADRE' in 'field list'
11/10/22 17:47:24 sp_servicios_b Ha ocurrido un error(42S22). 42S22 1054 Unknown column 'serv.PADRE' in 'field list'
11/10/22 17:47:27 sp_servicios_b Ha ocurrido un error(42S22). 42S22 1054 Unknown column 'serv.PADRE' in 'field list'
11/10/22 17:47:42 sp_servicios_b Ha ocurrido un error(42S22). 42S22 1054 Unknown column 'serv.PADRE' in 'field list'
11/10/22 17:47:49 sp_servicios_b Ha ocurrido un error(42S22). 42S22 1054 Unknown column 'serv.PADRE' in 'field list'
11/10/22 17:48:01 sp_servicios_b Ha ocurrido un error(42S22). 42S22 1054 Unknown column 'serv.PADRE' in 'field list'
11/10/22 17:48:43 sp_servicios_b Ha ocurrido un error(42S22). 42S22 1054 Unknown column 'serv.PADRE' in 'field list'
11/10/22 17:48:46 sp_servicios_b Ha ocurrido un error(42S22). 42S22 1054 Unknown column 'serv.PADRE' in 'field list'
11/10/22 17:49:23 sp_servicios_b Ha ocurrido un error(42S22). 42S22 1054 Unknown column 'serv.PADRE' in 'field list'
11/10/22 17:49:52 sp_servicios_b Ha ocurrido un error(42S22). 42S22 1054 Unknown column 'serv.PADRE' in 'field list'
11/10/22 17:49:58 sp_servicios_b Ha ocurrido un error(42S22). 42S22 1054 Unknown column 'serv.PADRE' in 'field list'
11/10/22 17:50:23 sp_servicios_b Ha ocurrido un error(42S22). 42S22 1054 Unknown column 'serv.PADRE' in 'field list'
11/10/22 17:50:28 sp_servicios_b Ha ocurrido un error(42S22). 42S22 1054 Unknown column 'serv.PADRE' in 'field list'
11/10/22 17:50:42 sp_servicios_b Ha ocurrido un error(42S22). 42S22 1054 Unknown column 'serv.PADRE' in 'field list'
11/10/22 17:50:45 sp_servicios_b Ha ocurrido un error(42S22). 42S22 1054 Unknown column 'serv.PADRE' in 'field list'
11/10/22 17:50:48 sp_servicios_b Ha ocurrido un error(42S22). 42S22 1054 Unknown column 'serv.PADRE' in 'field list'
11/10/22 17:50:54 sp_servicios_b Ha ocurrido un error(42S22). 42S22 1054 Unknown column 'serv.PADRE' in 'field list'
11/10/22 17:51:18 sp_servicios_b Ha ocurrido un error(42S22). 42S22 1054 Unknown column 'serv.PADRE' in 'field list'
11/10/22 17:51:20 sp_servicios_b Ha ocurrido un error(42S22). 42S22 1054 Unknown column 'serv.PADRE' in 'field list'
11/10/22 19:16:09 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [2002] Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder.

13/10/22 00:37:49 sp_pacientes_b Ha ocurrido un error(42000). 42000 1318 Incorrect number of arguments for PROCEDURE u808450138_checkup.sp_pacientes_b; expected 2, got 1
13/10/22 02:23:42 sp_clientes_b Ha ocurrido un error(42000). 42000 1318 Incorrect number of arguments for PROCEDURE u808450138_checkup.sp_clientes_b; expected 2, got 1
13/10/22 02:34:33 sp_pacientes_b Ha ocurrido un error(42000). 42000 1318 Incorrect number of arguments for PROCEDURE u808450138_checkup.sp_pacientes_b; expected 2, got 1
13/10/22 03:08:14 sp_pacientes_b Ha ocurrido un error(42000). 42000 1318 Incorrect number of arguments for PROCEDURE u808450138_checkup.sp_pacientes_b; expected 2, got 1
13/10/22 03:09:29 sp_pacientes_b Ha ocurrido un error(42000). 42000 1318 Incorrect number of arguments for PROCEDURE u808450138_checkup.sp_pacientes_b; expected 2, got 1
13/10/22 03:11:17 sp_pacientes_b Ha ocurrido un error(42000). 42000 1318 Incorrect number of arguments for PROCEDURE u808450138_checkup.sp_pacientes_b; expected 2, got 1
13/10/22 03:14:18 sp_pacientes_e Ha ocurrido un error(42000). 42000 1305 PROCEDURE u808450138_checkup.sp_pacientes_e does not exist
13/10/22 14:39:37 sp_pacientes_g Ha ocurrido un error(23000). 23000 1452 Cannot add or update a child row: a foreign key constraint fails (`u808450138_checkup`.`pacientes`, CONSTRAINT `FK_REFERENCE_5` FOREIGN KEY (`SEGMENTO_ID`) REFERENCES `segmentos` (`ID_SEGMENTO`) ON DELETE CASCADE ON UPDATE CASCADE)
13/10/22 14:40:48 sp_pacientes_g Ha ocurrido un error(23000). 23000 1452 Cannot add or update a child row: a foreign key constraint fails (`u808450138_checkup`.`pacientes`, CONSTRAINT `FK_REFERENCE_5` FOREIGN KEY (`SEGMENTO_ID`) REFERENCES `segmentos` (`ID_SEGMENTO`) ON DELETE CASCADE ON UPDATE CASCADE)
13/10/22 14:41:26 sp_pacientes_g Ha ocurrido un error(23000). 23000 1452 Cannot add or update a child row: a foreign key constraint fails (`u808450138_checkup`.`pacientes`, CONSTRAINT `FK_REFERENCE_5` FOREIGN KEY (`SEGMENTO_ID`) REFERENCES `segmentos` (`ID_SEGMENTO`) ON DELETE CASCADE ON UPDATE CASCADE)
13/10/22 16:28:41 sp_contactos_b Ha ocurrido un error(42S22). 42S22 1054 Unknown column 'con.NOMBNRE' in 'field list'
13/10/22 16:28:48 sp_contactos_b Ha ocurrido un error(42S22). 42S22 1054 Unknown column 'con.NOMBNRE' in 'field list'
13/10/22 16:28:54 sp_contactos_b Ha ocurrido un error(42S22). 42S22 1054 Unknown column 'con.NOMBNRE' in 'field list'
13/10/22 16:29:04 sp_contactos_b Ha ocurrido un error(42S22). 42S22 1054 Unknown column 'con.NOMBNRE' in 'field list'
13/10/22 16:29:05 sp_contactos_b Ha ocurrido un error(42S22). 42S22 1054 Unknown column 'con.NOMBNRE' in 'field list'
13/10/22 17:11:58 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
13/10/22 17:12:04 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
13/10/22 17:12:19 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
13/10/22 17:15:57 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
13/10/22 17:16:01 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
13/10/22 17:16:09 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
13/10/22 17:16:16 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
13/10/22 17:23:01 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
13/10/22 17:23:03 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
13/10/22 17:23:11 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
13/10/22 17:23:38 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
13/10/22 17:23:49 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
13/10/22 17:24:18 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
13/10/22 17:24:19 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
13/10/22 17:25:23 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
13/10/22 17:25:26 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
13/10/22 17:25:26 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
13/10/22 17:25:29 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
13/10/22 17:25:32 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
13/10/22 17:25:37 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
13/10/22 17:25:39 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
13/10/22 17:25:40 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
13/10/22 17:25:41 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
13/10/22 17:26:48 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
13/10/22 19:11:48 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
13/10/22 19:11:48 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
13/10/22 19:11:48 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
13/10/22 19:11:49 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
13/10/22 19:11:58 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
13/10/22 19:11:59 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
13/10/22 19:11:59 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
13/10/22 19:11:59 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
13/10/22 19:34:05 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
13/10/22 19:34:06 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
13/10/22 19:34:07 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
13/10/22 19:34:11 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
13/10/22 19:34:11 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
13/10/22 19:34:13 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
13/10/22 19:34:14 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
13/10/22 19:34:25 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
13/10/22 19:34:25 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
13/10/22 19:34:26 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
13/10/22 19:34:26 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
13/10/22 20:33:55 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
13/10/22 20:37:21 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
13/10/22 20:37:21 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
13/10/22 20:37:22 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
13/10/22 20:37:22 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
13/10/22 20:37:38 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
13/10/22 20:37:39 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
13/10/22 20:37:40 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
13/10/22 20:37:41 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
13/10/22 20:37:53 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
13/10/22 20:37:53 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
13/10/22 20:37:53 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
13/10/22 20:37:54 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
13/10/22 20:38:08 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
13/10/22 20:38:08 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
13/10/22 20:38:09 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
13/10/22 20:38:10 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
13/10/22 20:44:35 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [2002] Se ha intentado una operación de socket en un host no accesible.

13/10/22 20:44:35 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [2002] Se ha intentado una operación de socket en un host no accesible.

13/10/22 20:44:35 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [2002] Se ha intentado una operación de socket en un host no accesible.

13/10/22 20:44:38 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [2002] Se ha intentado una operación de socket en un host no accesible.

13/10/22 20:44:48 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [2002] Se ha intentado una operación de socket en un host no accesible.

13/10/22 20:44:48 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [2002] Se ha intentado una operación de socket en un host no accesible.

13/10/22 20:44:48 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [2002] Se ha intentado una operación de socket en un host no accesible.

13/10/22 20:44:48 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [2002] Se ha intentado una operación de socket en un host no accesible.

14/10/22 14:48:03 sp_servicios_b Ha ocurrido un error(42000). 42000 1318 Incorrect number of arguments for PROCEDURE u808450138_checkup.sp_servicios_b; expected 4, got 3
14/10/22 16:55:46 sp_servicios_b Ha ocurrido un error(42000). 42000 1318 Incorrect number of arguments for PROCEDURE u808450138_checkup.sp_servicios_b; expected 4, got 3
14/10/22 17:37:01 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
14/10/22 17:37:02 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
14/10/22 17:37:02 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
14/10/22 17:38:12 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
14/10/22 20:04:12 sp_usuarios_login_b Ha ocurrido un error(HY000). HY000 1449 The user specified as a definer ('u808450138_bimo'@'%') does not exist
14/10/22 20:04:16 sp_usuarios_login_b Ha ocurrido un error(HY000). HY000 1449 The user specified as a definer ('u808450138_bimo'@'%') does not exist
14/10/22 20:04:33 sp_usuarios_login_b Ha ocurrido un error(HY000). HY000 1449 The user specified as a definer ('u808450138_bimo'@'%') does not exist
14/10/22 20:04:36 sp_usuarios_login_b Ha ocurrido un error(HY000). HY000 1449 The user specified as a definer ('u808450138_bimo'@'%') does not exist
14/10/22 20:11:17 sp_usuarios_login_b Ha ocurrido un error(HY000). HY000 1449 The user specified as a definer ('root'@'%') does not exist
14/10/22 20:16:01 sp_usuarios_login_b Ha ocurrido un error(HY000). HY000 1449 The user specified as a definer ('root@localhost'@'%') does not exist
14/10/22 20:18:31 sp_usuarios_login_b Ha ocurrido un error(HY000). HY000 1449 The user specified as a definer ('ROOT'@'%') does not exist
14/10/22 20:20:50 sp_usuarios_login_b Ha ocurrido un error(HY000). HY000 1267 Illegal mix of collations (utf8_spanish2_ci,IMPLICIT) and (utf8_bin,NONE) for operation '='
14/10/22 20:23:01 sp_usuarios_login_b Ha ocurrido un error(42S22). 42S22 1054 Unknown column '_usuario' in 'where clause'
14/10/22 20:23:11 sp_usuarios_login_b Ha ocurrido un error(HY000). HY000 1267 Illegal mix of collations (utf8_spanish2_ci,IMPLICIT) and (utf8_bin,NONE) for operation '='
14/10/22 20:27:38 fn_connect_db Could not connect to the database  :SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client
14/10/22 20:28:36 fn_connect_db Could not connect to the database  :SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client
14/10/22 20:30:48 fn_connect_db Could not connect to the database  :SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client
14/10/22 20:31:08 fn_connect_db Could not connect to the database  :SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client
14/10/22 20:32:19 fn_connect_db Could not connect to the database  :SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client
14/10/22 20:33:35 fn_connect_db Could not connect to the database  :SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client
14/10/22 20:33:55 fn_connect_db Could not connect to the database  :SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client
14/10/22 20:33:56 fn_connect_db Could not connect to the database  :SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client
14/10/22 20:33:59 fn_connect_db Could not connect to the database  :SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client
14/10/22 20:33:59 fn_connect_db Could not connect to the database  :SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client
14/10/22 20:34:00 fn_connect_db Could not connect to the database  :SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client
14/10/22 20:34:32 fn_connect_db Could not connect to the database  :SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client
14/10/22 20:34:48 fn_connect_db Could not connect to the database  :SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client
14/10/22 20:36:24 fn_connect_db Could not connect to the database  :SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client
14/10/22 20:37:00 fn_connect_db Could not connect to the database  :SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client
14/10/22 20:37:19 fn_connect_db Could not connect to the database  :SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client
14/10/22 20:37:36 fn_connect_db Could not connect to the database  :SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client
14/10/22 20:38:17 fn_connect_db Could not connect to the database  :SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client
14/10/22 20:38:40 fn_connect_db Could not connect to the database  :SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client
14/10/22 20:38:55 fn_connect_db Could not connect to the database  :SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client
14/10/22 20:38:55 fn_connect_db Could not connect to the database  :SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client
14/10/22 20:39:42 fn_connect_db Could not connect to the database  :SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client
14/10/22 20:39:42 fn_connect_db Could not connect to the database  :SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client
14/10/22 20:56:52 sp_paquetes_g Ha ocurrido un error(42S22). 42S22 1054 Unknown column '_fecha_creacion' in 'field list'
14/10/22 20:59:20 sp_paquetes_g Ha ocurrido un error(42S22). 42S22 1054 Unknown column '_fecha_creacion' in 'field list'
14/10/22 20:59:59 sp_paquetes_g Ha ocurrido un error(23000). 23000 1062 Duplicate entry '0' for key 'PRIMARY'
14/10/22 21:01:30 sp_paquetes_g Ha ocurrido un error(23000). 23000 1062 Duplicate entry '0' for key 'PRIMARY'
14/10/22 21:02:38 sp_paquetes_g Ha ocurrido un error(23000). 23000 1062 Duplicate entry '0' for key 'PRIMARY'
14/10/22 21:23:08 sp_paquetes_g Ha ocurrido un error(23000). 23000 1062 Duplicate entry '0' for key 'PRIMARY'
14/10/22 21:24:33 sp_paquetes_g Ha ocurrido un error(23000). 23000 1062 Duplicate entry '0' for key 'PRIMARY'
14/10/22 21:27:18 sp_paquetes_g Ha ocurrido un error(23000). 23000 1062 Duplicate entry '0' for key 'PRIMARY'
14/10/22 21:31:42 sp_paquetes_g Ha ocurrido un error(23000). 23000 1062 Duplicate entry '0' for key 'PRIMARY'
14/10/22 21:32:31 sp_paquetes_g Ha ocurrido un error(23000). 23000 1062 Duplicate entry '0' for key 'PRIMARY'
14/10/22 21:33:05 sp_paquetes_g Ha ocurrido un error(23000). 23000 1062 Duplicate entry '0' for key 'PRIMARY'
17/10/22 17:16:12 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
17/10/22 17:16:29 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
17/10/22 17:16:50 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
17/10/22 17:17:39 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
17/10/22 17:18:04 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
17/10/22 17:18:10 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
17/10/22 17:55:55 sp_servicios_b Ha ocurrido un error(42000). 42000 1318 Incorrect number of arguments for PROCEDURE u808450138_checkup.sp_servicios_b; expected 4, got 3
17/10/22 18:06:17 sp_servicios_b Ha ocurrido un error(42000). 42000 1318 Incorrect number of arguments for PROCEDURE u808450138_checkup.sp_servicios_b; expected 4, got 3
19/10/22 20:46:18 sp_lista_de_trabajo Ha ocurrido un error(42S22). 42S22 1054 Unknown column 'pac.SEXO' in 'field list'
19/10/22 21:32:22 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [2002] Se ha intentado una operación de socket en un host no accesible.

19/10/22 21:32:22 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [2002] Se ha intentado una operación de socket en un host no accesible.

19/10/22 21:33:12 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [2002] Se ha intentado una operación de socket en un host no accesible.

19/10/22 21:33:12 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [2002] Se ha intentado una operación de socket en un host no accesible.

19/10/22 21:33:57 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [2002] Se ha intentado una operación de socket en un host no accesible.

19/10/22 21:33:57 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [2002] Se ha intentado una operación de socket en un host no accesible.

19/10/22 21:34:11 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [2002] Se ha intentado una operación de socket en un host no accesible.

19/10/22 21:34:11 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [2002] Se ha intentado una operación de socket en un host no accesible.

19/10/22 21:34:22 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [2002] Se ha intentado una operación de socket en un host no accesible.

19/10/22 21:34:22 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [2002] Se ha intentado una operación de socket en un host no accesible.

19/10/22 22:33:50 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [2002] Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder.

20/10/22 15:21:11 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [2002] Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder.

20/10/22 17:39:08 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [2002] Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder.

21/10/22 20:40:27 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [2002] Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder.

21/10/22 21:26:46 sp_turnos_g Ha ocurrido un error(42000). 42000 1318 Incorrect number of arguments for PROCEDURE u808450138_checkup.sp_turnos_g; expected 12, got 13
21/10/22 21:27:58 sp_turnos_g Ha ocurrido un error(42000). 42000 1318 Incorrect number of arguments for PROCEDURE u808450138_checkup.sp_turnos_g; expected 12, got 13
21/10/22 21:29:24 sp_turnos_g Ha ocurrido un error(42000). 42000 1318 Incorrect number of arguments for PROCEDURE u808450138_checkup.sp_turnos_g; expected 12, got 13
21/10/22 21:32:22 sp_turnos_g Ha ocurrido un error(42000). 42000 1318 Incorrect number of arguments for PROCEDURE u808450138_checkup.sp_turnos_g; expected 12, got 13
21/10/22 21:32:41 sp_turnos_g Ha ocurrido un error(42000). 42000 1318 Incorrect number of arguments for PROCEDURE u808450138_checkup.sp_turnos_g; expected 12, got 13
21/10/22 21:39:30 sp_turnos_g Ha ocurrido un error(42000). 42000 1318 Incorrect number of arguments for PROCEDURE u808450138_checkup.sp_turnos_g; expected 12, got 13
21/10/22 21:41:52 sp_turnos_g Ha ocurrido un error(42000). 42000 1318 Incorrect number of arguments for PROCEDURE u808450138_checkup.sp_turnos_g; expected 12, got 13
24/10/22 19:39:41 sp_turnos_g Ha ocurrido un error(42000). 42000 1318 Incorrect number of arguments for PROCEDURE u808450138_checkup.sp_turnos_g; expected 13, got 12
24/10/22 20:39:59 sp_turnos_g Ha ocurrido un error(42000). 42000 1318 Incorrect number of arguments for PROCEDURE u808450138_checkup.sp_turnos_g; expected 16, got 15
24/10/22 20:42:22 sp_turnos_g Ha ocurrido un error(42000). 42000 1318 Incorrect number of arguments for PROCEDURE u808450138_checkup.sp_turnos_g; expected 16, got 15
24/10/22 20:47:03 sp_turnos_g Ha ocurrido un error(42S22). 42S22 1054 Unknown column 'COMENARIO_RECHAZO' in 'field list'
24/10/22 20:47:53 sp_consultorio_antecedentes_g Ha ocurrido un error(23000). 23000 1452 Cannot add or update a child row: a foreign key constraint fails (`u808450138_checkup`.`consultorio_antecedentes`, CONSTRAINT `fk_consultorio_antecedentes_antecedentes_sub_tipo_1` FOREIGN KEY (`ANTECEDENTE_SUBTIPO_ID`) REFERENCES `antecedentes_sub_tipo` (`ID)
24/10/22 20:53:04 sp_consultorio_antecedentes_g Ha ocurrido un error(23000). 23000 1452 Cannot add or update a child row: a foreign key constraint fails (`u808450138_checkup`.`consultorio_antecedentes`, CONSTRAINT `fk_consultorio_antecedentes_antecedentes_respuestas_1` FOREIGN KEY (`ANTECEDENTE_RESPUESTA_ID`) REFERENCES `antecedentes_respuestas)
25/10/22 15:52:19 sp_buscar_paciente_por_estado Ha ocurrido un error(42S22). 42S22 1054 Unknown column 'pac.CLIENTE_ID' in 'field list'
25/10/22 15:54:23 sp_buscar_paciente_por_estado Ha ocurrido un error(42S22). 42S22 1054 Unknown column 'pac.CLIENTE_ID' in 'field list'
25/10/22 15:54:24 sp_buscar_paciente_por_estado Ha ocurrido un error(42S22). 42S22 1054 Unknown column 'pac.CLIENTE_ID' in 'field list'
25/10/22 16:00:25 sp_consultorio_antecedentes_g Ha ocurrido un error(23000). 23000 1452 Cannot add or update a child row: a foreign key constraint fails (`u808450138_checkup`.`consultorio_antecedentes`, CONSTRAINT `fk_consultorio_antecedentes_antecedentes_respuestas_1` FOREIGN KEY (`ANTECEDENTE_RESPUESTA_ID`) REFERENCES `antecedentes_respuestas)
25/10/22 16:02:24 sp_buscar_paciente_por_estado Ha ocurrido un error(42S22). 42S22 1054 Unknown column 'pac.CLIENTE_ID' in 'field list'
25/10/22 16:02:25 sp_buscar_paciente_por_estado Ha ocurrido un error(42S22). 42S22 1054 Unknown column 'pac.CLIENTE_ID' in 'field list'
25/10/22 18:07:21 sp_consultorio_antecedentes_g Ha ocurrido un error(23000). 23000 1452 Cannot add or update a child row: a foreign key constraint fails (`u808450138_checkup`.`consultorio_antecedentes`, CONSTRAINT `fk_consultorio_antecedentes_antecedentes_respuestas_1` FOREIGN KEY (`ANTECEDENTE_RESPUESTA_ID`) REFERENCES `antecedentes_respuestas)
25/10/22 18:14:11 sp_buscar_paciente_por_estado Ha ocurrido un error(42S22). 42S22 1054 Unknown column 'pac.CLIENTE_ID' in 'field list'
25/10/22 18:14:33 sp_buscar_paciente_por_estado Ha ocurrido un error(42S22). 42S22 1054 Unknown column 'pac.CLIENTE_ID' in 'field list'
25/10/22 20:01:28 sp_turnos_g Ha ocurrido un error(23000). 23000 1452 Cannot add or update a child row: a foreign key constraint fails (`u808450138_checkup`.`turnos`, CONSTRAINT `fk_turnos_segmentos_1` FOREIGN KEY (`SEGMENTO_ID`) REFERENCES `segmentos` (`ID_SEGMENTO`))
25/10/22 20:03:58 sp_consultorio_antecedentes_g Ha ocurrido un error(23000). 23000 1452 Cannot add or update a child row: a foreign key constraint fails (`u808450138_checkup`.`consultorio_antecedentes`, CONSTRAINT `fk_consultorio_antecedentes_antecedentes_respuestas_1` FOREIGN KEY (`ANTECEDENTE_RESPUESTA_ID`) REFERENCES `antecedentes_respuestas)
26/10/22 19:25:24 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [2002] Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder.

27/10/22 19:23:45 sp_servicios_g Ha ocurrido un error(42000). 42000 1318 Incorrect number of arguments for PROCEDURE u808450138_checkup.sp_servicios_g; expected 20, got 19
27/10/22 19:23:56 sp_servicios_g Ha ocurrido un error(42000). 42000 1318 Incorrect number of arguments for PROCEDURE u808450138_checkup.sp_servicios_g; expected 20, got 19
27/10/22 19:53:15 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
27/10/22 19:53:16 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
27/10/22 19:54:33 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
27/10/22 20:22:16 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
27/10/22 20:22:16 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
27/10/22 20:22:17 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
28/10/22 17:12:39 sp_consultorio_antecedentes_g Ha ocurrido un error(23000). 23000 1452 Cannot add or update a child row: a foreign key constraint fails (`u808450138_checkup`.`consultorio_antecedentes`, CONSTRAINT `fk_consultorio_antecedentes_antecedentes_respuestas_1` FOREIGN KEY (`ANTECEDENTE_RESPUESTA_ID`) REFERENCES `antecedentes_respuestas)
28/10/22 17:13:13 sp_recepcion_detalle_paquete_g Ha ocurrido un error(42000). 42000 1305 PROCEDURE u808450138_checkup.sp_recepcion_detalle_paquete_g does not exist
28/10/22 18:28:16 sp_lista_de_trabajo Ha ocurrido un error(42000). 42000 1318 Incorrect number of arguments for PROCEDURE u808450138_checkup.sp_lista_de_trabajo; expected 3, got 2
29/10/22 13:09:35 sp_consultorio_antecedentes_g Ha ocurrido un error(23000). 23000 1452 Cannot add or update a child row: a foreign key constraint fails (`u808450138_checkup`.`consultorio_antecedentes`, CONSTRAINT `fk_consultorio_antecedentes_antecedentes_respuestas_1` FOREIGN KEY (`ANTECEDENTE_RESPUESTA_ID`) REFERENCES `antecedentes_respuestas)
29/10/22 13:10:01 sp_recepcion_detalle_paquete_g Ha ocurrido un error(42000). 42000 1305 PROCEDURE u808450138_checkup.sp_recepcion_detalle_paquete_g does not exist
29/10/22 13:12:32 sp_recepcion_detalle_paquete_g Ha ocurrido un error(42000). 42000 1305 PROCEDURE u808450138_checkup.sp_recepcion_detalle_paquete_g does not exist
29/10/22 15:52:13 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [2002] Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder.

29/10/22 16:19:29 sp_paquetes_actualizar_costo Ha ocurrido un error(42000). 42000 1318 Incorrect number of arguments for PROCEDURE u808450138_checkup.sp_paquetes_actualizar_costo; expected 5, got 4
29/10/22 16:19:29 sp_paquetes_actualizar_costo Ha ocurrido un error(42000). 42000 1318 Incorrect number of arguments for PROCEDURE u808450138_checkup.sp_paquetes_actualizar_costo; expected 5, got 4
29/10/22 16:29:56 sp_paquetes_actualizar_costo Ha ocurrido un error(42000). 42000 1318 Incorrect number of arguments for PROCEDURE u808450138_checkup.sp_paquetes_actualizar_costo; expected 5, got 4
29/10/22 16:29:56 sp_paquetes_actualizar_costo Ha ocurrido un error(42000). 42000 1318 Incorrect number of arguments for PROCEDURE u808450138_checkup.sp_paquetes_actualizar_costo; expected 5, got 4
29/10/22 16:44:44 sp_paquetes_actualizar_costo Ha ocurrido un error(42000). 42000 1318 Incorrect number of arguments for PROCEDURE u808450138_checkup.sp_paquetes_actualizar_costo; expected 5, got 4
29/10/22 16:44:44 sp_paquetes_actualizar_costo Ha ocurrido un error(42000). 42000 1318 Incorrect number of arguments for PROCEDURE u808450138_checkup.sp_paquetes_actualizar_costo; expected 5, got 4
31/10/22 16:31:58 sp_servicios_b Ha ocurrido un error(42000). 42000 1318 Incorrect number of arguments for PROCEDURE u808450138_checkup.sp_servicios_b; expected 5, got 4
31/10/22 16:32:27 sp_servicios_b Ha ocurrido un error(42000). 42000 1318 Incorrect number of arguments for PROCEDURE u808450138_checkup.sp_servicios_b; expected 5, got 4
31/10/22 16:32:34 sp_servicios_b Ha ocurrido un error(42000). 42000 1318 Incorrect number of arguments for PROCEDURE u808450138_checkup.sp_servicios_b; expected 5, got 4
31/10/22 16:32:50 sp_servicios_b Ha ocurrido un error(42000). 42000 1318 Incorrect number of arguments for PROCEDURE u808450138_checkup.sp_servicios_b; expected 5, got 4
31/10/22 16:32:51 sp_servicios_b Ha ocurrido un error(42000). 42000 1318 Incorrect number of arguments for PROCEDURE u808450138_checkup.sp_servicios_b; expected 5, got 4
31/10/22 16:32:55 sp_servicios_b Ha ocurrido un error(42000). 42000 1318 Incorrect number of arguments for PROCEDURE u808450138_checkup.sp_servicios_b; expected 5, got 4
31/10/22 16:32:56 sp_servicios_b Ha ocurrido un error(42000). 42000 1318 Incorrect number of arguments for PROCEDURE u808450138_checkup.sp_servicios_b; expected 5, got 4
31/10/22 16:34:18 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [2002] Se ha anulado una conexión establecida por el software en su equipo host..

31/10/22 16:34:30 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [2002] Se ha intentado una operación de socket en una red no accesible.

31/10/22 16:35:01 sp_servicios_b Ha ocurrido un error(42000). 42000 1318 Incorrect number of arguments for PROCEDURE u808450138_checkup.sp_servicios_b; expected 5, got 4
31/10/22 16:42:18 sp_servicios_b Ha ocurrido un error(42000). 42000 1318 Incorrect number of arguments for PROCEDURE u808450138_checkup.sp_servicios_b; expected 5, got 4
31/10/22 16:42:21 sp_servicios_b Ha ocurrido un error(42000). 42000 1318 Incorrect number of arguments for PROCEDURE u808450138_checkup.sp_servicios_b; expected 5, got 4
31/10/22 17:33:52 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [2002] Se ha intentado una operación de socket en un host no accesible.

31/10/22 17:33:52 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [2002] Se ha intentado una operación de socket en un host no accesible.

31/10/22 17:33:52 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [2002] Se ha intentado una operación de socket en un host no accesible.

31/10/22 17:33:52 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [2002] Se ha intentado una operación de socket en un host no accesible.

31/10/22 17:35:40 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [2002] Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder.

31/10/22 18:16:42 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [2002] Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder.

31/10/22 18:21:34 sp_recepcion_detalle_paquete_g Ha ocurrido un error(42000). 42000 1305 PROCEDURE u808450138_checkup.sp_recepcion_detalle_paquete_g does not exist
01/11/22 23:16:13 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [2002] Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder.

01/11/22 23:16:20 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [2002] Se ha anulado una conexión establecida por el software en su equipo host..

01/11/22 23:16:20 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [2002] Se ha intentado una operación de socket en una red no accesible.

01/11/22 23:16:20 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [2002] Se ha intentado una operación de socket en una red no accesible.

02/11/22 22:03:11 sp_historial_servicios_paciente Ha ocurrido un error(42S22). 42S22 1054 Unknown column 'pac_det.CHECKED' in 'field list'
02/11/22 22:43:02 sp_historial_servicios_paciente Ha ocurrido un error(42S22). 42S22 1054 Unknown column 'pac_det.CHECKED' in 'field list'
03/11/22 21:11:31 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [2002] Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder.

