25/11/22 16:27:36 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [2002] Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder.

25/11/22 19:39:28 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [2006] MySQL server has gone away
29/11/22 10:57:49 sp_consultorio_exploracion_g Ha ocurrido un error(42000). 42000 1305 PROCEDURE u808450138_checkup.sp_consultorio_exploracion_g does not exist
29/11/22 11:01:27 sp_consultorio_exploracion_g Ha ocurrido un error(42000). 42000 1305 PROCEDURE u808450138_checkup.sp_consultorio_exploracion_g does not exist
29/11/22 12:25:57 sp_consultorio_recetas_b Ha ocurrido un error(42S22). 42S22 1054 Unknown column 'cns_rec.MEDICAMENTO' in 'field list'
04/12/22 18:20:28 sp_recepcion_detalle_paciente_g Ha ocurrido un error(23000). 23000 1452 Cannot add or update a child row: a foreign key constraint fails (`u808450138_checkup`.`cargos_turno`, CONSTRAINT `fk_cargos_turno_servicios_1` FOREIGN KEY (`SERVICIO_ID`) REFERENCES `servicios` (`ID_SERVICIO`) ON DELETE CASCADE ON UPDATE CASCADE)
04/12/22 18:34:00 sp_recepcion_detalle_paciente_g Ha ocurrido un error(23000). 23000 1452 Cannot add or update a child row: a foreign key constraint fails (`u808450138_checkup`.`cargos_turno`, CONSTRAINT `fk_cargos_turno_servicios_1` FOREIGN KEY (`SERVICIO_ID`) REFERENCES `servicios` (`ID_SERVICIO`) ON DELETE CASCADE ON UPDATE CASCADE)
04/12/22 18:34:30 sp_recepcion_detalle_paciente_g Ha ocurrido un error(23000). 23000 1452 Cannot add or update a child row: a foreign key constraint fails (`u808450138_checkup`.`cargos_turno`, CONSTRAINT `fk_cargos_turno_servicios_1` FOREIGN KEY (`SERVICIO_ID`) REFERENCES `servicios` (`ID_SERVICIO`) ON DELETE CASCADE ON UPDATE CASCADE)
05/12/22 11:17:28 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
05/12/22 11:17:56 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
05/12/22 11:36:38 sp_recepcion_detalle_paciente_g Ha ocurrido un error(23000). 23000 1452 Cannot add or update a child row: a foreign key constraint fails (`u808450138_checkup`.`cargos_turno`, CONSTRAINT `fk_cargos_turno_servicios_1` FOREIGN KEY (`SERVICIO_ID`) REFERENCES `servicios` (`ID_SERVICIO`) ON DELETE CASCADE ON UPDATE CASCADE)
05/12/22 17:29:09 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [2002] Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder.

05/12/22 17:29:30 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [2002] Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder.

12/12/22 11:53:26 sp_consultorio_odontograma_g Ha ocurrido un error(42000). 42000 1318 Incorrect number of arguments for PROCEDURE u808450138_checkup.sp_consultorio_odontograma_g; expected 7, got 6
12/12/22 11:54:09 sp_consultorio_odontograma_g Ha ocurrido un error(42000). 42000 1318 Incorrect number of arguments for PROCEDURE u808450138_checkup.sp_consultorio_odontograma_g; expected 7, got 6
12/12/22 12:00:54 sp_consultorio_odontograma_g Ha ocurrido un error(42000). 42000 1318 Incorrect number of arguments for PROCEDURE u808450138_checkup.sp_consultorio_odontograma_g; expected 7, got 6
12/12/22 15:36:54 sp_consultorio_odontograma_g Ha ocurrido un error(42000). 42000 1318 Incorrect number of arguments for PROCEDURE u808450138_checkup.sp_consultorio_odontograma_g; expected 7, got 6
12/12/22 15:37:53 sp_consultorio_odontograma_g Ha ocurrido un error(42000). 42000 1318 Incorrect number of arguments for PROCEDURE u808450138_checkup.sp_consultorio_odontograma_g; expected 7, got 6
12/12/22 15:59:04 sp_consultorio_odontograma_g Ha ocurrido un error(42000). 42000 1318 Incorrect number of arguments for PROCEDURE u808450138_checkup.sp_consultorio_odontograma_g; expected 7, got 6
12/12/22 16:13:00 sp_consultorio_odontograma_g Ha ocurrido un error(23000). 23000 1452 Cannot add or update a child row: a foreign key constraint fails (`u808450138_checkup`.`consultorio_odontograma`, CONSTRAINT `fk_consultorio_odontograma_consultorio_pieza_dental_caras_1` FOREIGN KEY (`CARA_ID`) REFERENCES `consultorio_pieza_dental_caras` (`I)
13/12/22 10:34:17 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [2002] Se ha intentado una operación de socket en una red no accesible.

19/12/22 15:10:20 sp_recepcion_detalle_paciente_g Ha ocurrido un error(23000). 23000 1452 Cannot add or update a child row: a foreign key constraint fails (`u808450138_checkup`.`cargos_turno`, CONSTRAINT `fk_cargos_turno_servicios_1` FOREIGN KEY (`SERVICIO_ID`) REFERENCES `servicios` (`ID_SERVICIO`) ON DELETE CASCADE ON UPDATE CASCADE)
19/12/22 15:11:13 sp_recepcion_detalle_paciente_g Ha ocurrido un error(23000). 23000 1452 Cannot add or update a child row: a foreign key constraint fails (`u808450138_checkup`.`cargos_turno`, CONSTRAINT `fk_cargos_turno_servicios_1` FOREIGN KEY (`SERVICIO_ID`) REFERENCES `servicios` (`ID_SERVICIO`) ON DELETE CASCADE ON UPDATE CASCADE)
19/12/22 15:15:19 sp_recepcion_detalle_paciente_g Ha ocurrido un error(23000). 23000 1452 Cannot add or update a child row: a foreign key constraint fails (`u808450138_checkup`.`cargos_turno`, CONSTRAINT `fk_cargos_turno_servicios_1` FOREIGN KEY (`SERVICIO_ID`) REFERENCES `servicios` (`ID_SERVICIO`) ON DELETE CASCADE ON UPDATE CASCADE)
19/12/22 16:32:13 sp_recepcion_detalle_paciente_g Ha ocurrido un error(23000). 23000 1452 Cannot add or update a child row: a foreign key constraint fails (`u808450138_checkup`.`cargos_turno`, CONSTRAINT `fk_cargos_turno_servicios_1` FOREIGN KEY (`SERVICIO_ID`) REFERENCES `servicios` (`ID_SERVICIO`) ON DELETE CASCADE ON UPDATE CASCADE)
20/12/22 10:10:40 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
20/12/22 10:10:42 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
20/12/22 10:10:44 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
20/12/22 10:10:46 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
20/12/22 10:10:47 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
20/12/22 10:10:49 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
20/12/22 10:10:50 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
20/12/22 10:10:51 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
20/12/22 10:10:52 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
20/12/22 10:10:54 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
20/12/22 10:10:54 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
20/12/22 10:10:56 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
20/12/22 10:10:57 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
20/12/22 10:10:58 fn_connect_db Could not connect to the database u808450138_checkup :SQLSTATE[HY000] [1226] User 'u808450138_bimo' has exceeded the 'max_connections_per_hour' resource (current value: 500)
21/12/22 09:59:31 sp_informacion_paciente Ha ocurrido un error(42000). 42000 1318 Incorrect number of arguments for PROCEDURE u808450138_checkup.sp_informacion_paciente; expected 1, got 3
21/12/22 10:01:30 sp_informacion_paciente Ha ocurrido un error(42000). 42000 1318 Incorrect number of arguments for PROCEDURE u808450138_checkup.sp_informacion_paciente; expected 1, got 3
